[package]
name = "bex_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bex = "0.2.0"
warp = "0.3.5"
